### ISSUE TITLE
Optionally pass the location to wrapping functions 

### ISSUE THREAD

**Issue by Chris00** [mjambon/atdgen#34]
When using [wrapping functions](https://mjambon.github.io/atdgen-doc/atdgen#using-a-custom-wrapper), it would be nice to ask atdgen to pass the location to the wrapper function.  This is useful to report errors for example.  (A function in `Yojson` to report an error with a location — using the same format as the default errors raised by Yoson/atdgen — would also be nice.)

**Comment by mjambon** [comment]
This issue was moved to mjambon/atd#100
