### ISSUE TITLE
please make it more convenient to pretty-print large JSON objects

### ISSUE THREAD

**Issue by josch** [mjambon/atdgen#43]
Hi,

due to OCaml string length limitations (especially on 32 bits) I try to avoid ever having the JSON results stored in a string. Currently I'm doing something like this:

```ocaml
let ob = Bi_outbuf.create_channel_writer stdout in
Datatypes_j.write_stats ob result;
Bi_outbuf.flush_channel_writer ob;
```

But what if I want to pretty print the results using Yojson? Doing the following will not work:

```ocaml
let r = Datatypes_j.string_of_stats result in
Yojson.Safe.pretty_to_channel ~std:true stdout (Yojson.Safe.from_string r);
```

because `r` is a string and might not be able to hold the entire JSON data. What are my options? I see the following two:

 1. use `Bi_outbuf.create_channel_writer` to write to a temporary file and then use `Yojson.Safe.from_file` to read from that file
 1. write the atdgen results with a custom `make_room` function which appends everything to a custom buffer object which is able to handle more than the maximum string length and then use `Yojson.Safe.from_lexer` together with a custom Lexer created with `Lexer.from_function` which reads from my buffer object

But both do not seem ideal. Using a temporary file instead of staying in memory seems clunky while the second option requires lots of wrapper code.

Maybe there is an option which lets me keep the biniou object from atdgen and pass it to Yojson directly? I see that Yojson uses biniou in its reader too.

Am I missing something?

**Comment by mjambon** [comment]
I don't see a simple solution for the user at this time. Atdgen wasn't designed to support incremental reads and writes.

Beware that pretty-printing large objects can be very slow, depending on their structure. In general, large JSON object should be avoided. Instead, people should use independent whitespace-separated JSON objects (typically one per line) and process them one by one. Atdgen offers a module to read and write such streams, it's `Ag_util`. Documentation is lacking, but it's fully supported. See https://github.com/mjambon/atdgen/blob/master/src/ag_util.mli

Another workaround would be to estimate the size of the JSON data and simply not pretty-print objects beyond a certain size.

It's also possible to use a unix pipe and the external program `ydump` for pretty-printing, e.g. `my_program_that_writes_json | ydump` or `Unix.open_process_full "ydump" [| "ydump" |]`.

**Comment by josch** [comment]
Hi,

in fact, speed was never an issue for me, even with large JSON objects on 64bit systems.

Splitting into multiple objects, one per line would remove some of the reasons i'm using json in the first place. I could then just dumb things down to tab delimetered, line-based data and forget about json.

Unfortunately my data is in a tree-like format, so you will agree that this is hard to split into lines of individual json unless I add complexity by adding IDs which link the individual lines back into a full tree...

Not pretty printing at all would've been my default but fortunately...

...your last option seems to completely satisfy my needs as `ydump` never seems to represent the whole input or output json as a single string and will thus not hit the ocaml string length limits but is only limited by the system memory. It is thus able to pretty print even 2GB big json output.

Thanks for the tip!
