### ISSUE TITLE
Using reserved words

### ISSUE THREAD

**Issue by jveiga** [mjambon/atdgen#53]
Hi, I was trying this project out, great work :)

I was trying to use something like
```bash
cat object.atd
type object = {
   type: string;
}
```
And I get 
```bash
atdgen -t object.atd                  
File "object.atd", line 2, characters 1-5:
Expecting type expression
```
I understand that type is probably a reserved word, but is there a way to use it?

**Comment by mjambon** [comment]
Yes, there is. You need to use another field name than `type` in the atd definition and specify that you want the json field name to by `type`:
```
type obj = {
   type_ <json name="type">: string;
}
```
Note that I renamed `object` to `obj` because `object` is an OCaml keyword and we don't support `type object <ocaml name="obj"> = ...` at this time.

**Comment by jveiga** [comment]
Thank you :)
