### ISSUE TITLE
Support generic fallback for unknown tag read from the tag_field field

### ISSUE THREAD

**Issue by mjambon** [mjambon/atdgen#54]
Original question/request: https://github.com/mirage/ocaml-github/pull/128#issuecomment-242939595

```ocaml
type hook_config = [
   | Web <json name="web"> of web_hook_config
 ]

type hook = {
  ...
  config <json tag_field="name">: hook_config;
  }
```

Sample json that is supported:

```
{ "name": "web"; "config": { ... }}
```

Sample json that is not supported because we don't know the full list of legal tags (contents of the `name` field):

```
{ "name": "travis"; "config": { ... }}
```

**Comment by mjambon** [comment]
This would be useful for to solve the problem at hand, but it also adds complexity to the source code of atdgen, which has become hard to manage.

Something useful here could be to declare a fallback case, which would keep the data as a json AST. This would avoid an error and would preserve the original data, allowing it to be inspected, reported, or converted back to json.

Perhaps we should support an `untyped` annotation as follows:

type hook_config = [
   | Web <json name="web"> of web_hook_config
   | Other <json untyped> of (string * json)
 ]

**Comment by dsheets** [comment]
See <https://github.com/mjambon/atdgen/pull/25#issuecomment-62309955> for a similar feature discussed during the original PR.
