### ISSUE TITLE
Also provide /usr/bin/adtgen without ocamlopt

### ISSUE THREAD

**Issue by josch** [mjambon/atdgen#58]
Hi,

it seems that currently, an executable called `atdgen` is only installed into `$(BINDIR)/` if the `opt` target gets executed beforehand. This means that on architectures without ocamlopt, `$(BINDIR)/` will contain a different interface than on architectures with ocamlopt. This in turn means, that an architecture-independent other program cannot rely on the existance of, for example, `/usr/bin/atdgen` but _also_ has to test for `/usr/bin/atdgen.run`.

Would it be possible for atdgen to provide an architecture independent interface to the `atdgen` executable? That way, users of `atdgen` would not have to check which executable is available but could trust a single interface.

For example, it would be possible to install a symlink from `atdgen` to `atdgen.run` on platforms that come without ocamlopt.

Would that be possible?

**Comment by mjambon** [comment]
This issue was moved to mjambon/atd#91
